<span style = "font-size:20px"> **(1) Create a one dimensinoal array that contains numbers from 1 to 10.**</span><br>
    **Use `np.array()`**

In [5]:
import numpy as np
ar_1 = np.array(range(1, 11))
print(ar_1.shape)


(10,)


<span style = "font-size:20px"> **(2) Create the following arrays** </span><br>
[[15, 12, 9, 22],<br>
 [21, 7, 10, 14],<br>
 [31, 10, 33, 8]]<br>
 **Use `np.array()`**

In [7]:
ar_2 = np.array([[15, 12, 9, 22],
[21, 7, 10, 14],
[31, 10, 33, 8]])

print(ar_2)

[[15 12  9 22]
 [21  7 10 14]
 [31 10 33  8]]


<span style = "font-size:20px"> **(3) Create an array full of zeros and of shape (2,3).**</span><br>
    **Use `np.zeros()`**

In [8]:
ar_zero = np.zeros((2, 3))

print(ar_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


<span style = "font-size:20px"> **(4) Create an array that contains odd numbers from 1 to 1000.**</span><br>
**Use: `np.arange()`**

In [14]:
ar_odd = np.arange(1, 1000, 2)

print(ar_odd.shape)

(500,)


<span style = "font-size:20px"> **(6) Show what `ndim` do.**</span><br>

In [13]:
#the atribute "ndim"(number of dimensions) shows many axes (or dimensions) an array has.
#ex:
print("ar_1 dimensions:", ar_1.ndim)
print("ar_2 dimensions:", ar_2.ndim)
print("ar_zero dimensions:", ar_zero.ndim)

ar_1 dimensions: 1
ar_2 dimensions: 2
ar_zero dimensions: 2


<span style = "font-size:20px"> **(7) What is the difference between `shape` and `size`?**</span><br>
**Explain with words and with `code`.**

In [17]:
# shape:shows the structure or geometry of an array, ex: array of (3, 4) means the array has 3 rows and 4 columns

# size: shows the total number of items inside an array, ex: if the shape of an array is (3, 4) its size is 12

# shape of ar_2:
print("Shape:", ar_2.shape)

# size 0f ar_2:
print("Size:", ar_2.size)

Shape: (3, 4)
Size: 12


<span style = "font-size:20px"> **(8) Flat the following array.**</span><br>

In [21]:
arr = np.array([[i, 2*i, 3*i] for i in range(3, 300)])
# write your code here
ar_flat = arr.flatten()
print(ar_flat)

[  3   6   9   4   8  12   5  10  15   6  12  18   7  14  21   8  16  24
   9  18  27  10  20  30  11  22  33  12  24  36  13  26  39  14  28  42
  15  30  45  16  32  48  17  34  51  18  36  54  19  38  57  20  40  60
  21  42  63  22  44  66  23  46  69  24  48  72  25  50  75  26  52  78
  27  54  81  28  56  84  29  58  87  30  60  90  31  62  93  32  64  96
  33  66  99  34  68 102  35  70 105  36  72 108  37  74 111  38  76 114
  39  78 117  40  80 120  41  82 123  42  84 126  43  86 129  44  88 132
  45  90 135  46  92 138  47  94 141  48  96 144  49  98 147  50 100 150
  51 102 153  52 104 156  53 106 159  54 108 162  55 110 165  56 112 168
  57 114 171  58 116 174  59 118 177  60 120 180  61 122 183  62 124 186
  63 126 189  64 128 192  65 130 195  66 132 198  67 134 201  68 136 204
  69 138 207  70 140 210  71 142 213  72 144 216  73 146 219  74 148 222
  75 150 225  76 152 228  77 154 231  78 156 234  79 158 237  80 160 240
  81 162 243  82 164 246  83 166 249  84 168 252  8

<span style = "font-size:20px"> **(9) Transpose the following array.**</span><br>

In [25]:
arr = np.array([[[[j, j + 1] for j in range(5)]] for i in range(3)])
# write your code here
ar_transposed = arr.T

print(ar_transposed)

[[[[0 0 0]]

  [[1 1 1]]

  [[2 2 2]]

  [[3 3 3]]

  [[4 4 4]]]


 [[[1 1 1]]

  [[2 2 2]]

  [[3 3 3]]

  [[4 4 4]]

  [[5 5 5]]]]


<span style = "font-size:20px"> **(10) How many unique values are in the following array and print them.**</span><br>

In [27]:
countries = np.array(['canada','spain','india','usa','canada','england','japan','germany','india','england','egypt','england','japan','egypt','india','japan'
                     ,'china','germany','india','china','canada','india','canada''egypt','china','germany','japan','russia'
                    ,'england','usa','germany','china','russia''germany''china','spain''spain','canada','germany','spain',
                    'china','canada','china''canada','germany','russia','japan','india','russia','egypt', 'canada',
                    'spain','india','usa','canada','england','japan','germany','india','england','egypt','england','japan',
                    'egypt','india','japan','china','germany','india','china','canada','india','canada''egypt','china','germany','japan','russia'
                      ,'england','usa','germany','china','russia''germany''china','spain''spain','canada','germany','spain',
                      'china','canada','china''canada','germany','russia','japan','india','russia','egypt'])
# write your code here
# Be smart and use code

unique_countries = np.unique(countries)

unique_num = unique_countries.size

print(f"number of unique values: {unique_num}\n")
print(f"Unique values: {unique_countries}")

number of unique values: 14

Unique values: ['canada' 'canadaegypt' 'china' 'chinacanada' 'egypt' 'england' 'germany'
 'india' 'japan' 'russia' 'russiagermanychina' 'spain' 'spainspain' 'usa']


(11) Given the following arrays:

```python
import numpy as np

A = np.arange(1, 13).reshape(3, 4)
B = np.array([10, 20, 30])

### 1. Shapes
What is the shape of:
- `A[1]`  
- `B`

---

### 2. Broadcasting Issue
Why does the following operation fail?

```python
result = A[1] * B



### Question : The Embedding Challenge
You are given two arrays:
1. `array_a`: A 5x5 grid filled with the number `9`.
2. `array_b`: A 3x3 grid filled with the number `1`.

**Task:** Use slicing to "embed" `array_b` into the center of `array_a`. Do **not** use loops.

**Expected Result:**
```python
[[9, 9, 9, 9, 9],
 [9, 1, 1, 1, 9],
 [9, 1, 1, 1, 9],
 [9, 1, 1, 1, 9],
 [9, 9, 9, 9, 9]]

In [30]:
array_a = np.full((5, 5), 9)
array_b = np.ones((3, 3))

# Your code here (Modify array_a using a slice):
#?

print(array_a)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


##  NumPy Dimensions – Questions

1. What is the shape of `a` and `b`?  

2. What does `(3,)` mean in NumPy? Why is there a comma?  

3. How many dimensions does each array have?  

4. What does each dimension (axis) represent in `b`?  

5. Is `(3,)` the same as `(3, 1)`? Explain the difference.  

In [ ]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])